# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nitin/sanity

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nitin/sanity

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nitin/sanity/CMakeFiles /home/nitin/sanity/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nitin/sanity/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sol_runtime

# Build rule for target.
sol_runtime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sol_runtime
.PHONY : sol_runtime

# fast build rule for target.
sol_runtime/fast:
	$(MAKE) -f CMakeFiles/sol_runtime.dir/build.make CMakeFiles/sol_runtime.dir/build
.PHONY : sol_runtime/fast

my_ispc.o: my_ispc.cpp.o

.PHONY : my_ispc.o

# target to build an object file
my_ispc.cpp.o:
	$(MAKE) -f CMakeFiles/sol_runtime.dir/build.make CMakeFiles/sol_runtime.dir/my_ispc.cpp.o
.PHONY : my_ispc.cpp.o

my_ispc.i: my_ispc.cpp.i

.PHONY : my_ispc.i

# target to preprocess a source file
my_ispc.cpp.i:
	$(MAKE) -f CMakeFiles/sol_runtime.dir/build.make CMakeFiles/sol_runtime.dir/my_ispc.cpp.i
.PHONY : my_ispc.cpp.i

my_ispc.s: my_ispc.cpp.s

.PHONY : my_ispc.s

# target to generate assembly for a file
my_ispc.cpp.s:
	$(MAKE) -f CMakeFiles/sol_runtime.dir/build.make CMakeFiles/sol_runtime.dir/my_ispc.cpp.s
.PHONY : my_ispc.cpp.s

my_x86.o: my_x86.cpp.o

.PHONY : my_x86.o

# target to build an object file
my_x86.cpp.o:
	$(MAKE) -f CMakeFiles/sol_runtime.dir/build.make CMakeFiles/sol_runtime.dir/my_x86.cpp.o
.PHONY : my_x86.cpp.o

my_x86.i: my_x86.cpp.i

.PHONY : my_x86.i

# target to preprocess a source file
my_x86.cpp.i:
	$(MAKE) -f CMakeFiles/sol_runtime.dir/build.make CMakeFiles/sol_runtime.dir/my_x86.cpp.i
.PHONY : my_x86.cpp.i

my_x86.s: my_x86.cpp.s

.PHONY : my_x86.s

# target to generate assembly for a file
my_x86.cpp.s:
	$(MAKE) -f CMakeFiles/sol_runtime.dir/build.make CMakeFiles/sol_runtime.dir/my_x86.cpp.s
.PHONY : my_x86.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sol_runtime"
	@echo "... my_ispc.o"
	@echo "... my_ispc.i"
	@echo "... my_ispc.s"
	@echo "... my_x86.o"
	@echo "... my_x86.i"
	@echo "... my_x86.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

